spring:
  application:
    name: dependency-service

server:
  port: ${PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME:${random.value}}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
