spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: consumer-service-api
          uri: lb://consumer-service
          predicates:
            - Path=/api/**

server:
  port: ${PORT:8088}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME:${random.value}}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
